baseURL = 'https://louisbel.github.io/notes/'
relativeURLs = false
languageCode = 'en-us'
title = 'Louis Belpaire'
theme = 'Typo'

# Disable tags, actually, they are rendered as a list, but the idea is to disable them.
disableKinds = ['taxonomy']

# Google analytics code
googleAnalytics = "G-F2FPL4RJD1"

[params]
# Appearance
theme = 'auto'

pygmentsUseClasses = true
pygmentsCodefences = true
   
# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntroTitle = 'Hi!'
homeIntroContent = """
Welcome to my research lab where I explore the ever-evolving landscape of tech & digital marketing, 
fueled by curiosity and coffee beans ☕. All opinions are my own.
"""

# Collection to display on home page: 
# in this case we would display content/posts pages
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100
# Display summaries under post list entries
listSummaries = true
# List entries date format
listDateFormat = '2 Jan 2006'

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/belpaire/"

# Main menu pages
[[params.menu]]
name = "home"
url = "/notes"

[[params.menu]]
name = "posts"
url = "/notes/posts"

[[params.menu]]
name = "resume"
url = "/notes/resume"

# giscus conf, for more detail, see https://giscus.app/
[params.giscus]
  enable = true
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = "pathname"
  theme = "light"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'rainbow_dash'

[[module.mounts]]
source = 'static'
target = 'static'
